commenting steps

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,30 +29,30 @@ jobs:
       - run:
         name: Test
         command: go test -v -race ./...
-      - run:
-        name: Login to Docker
-        command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
-      - run:
-        name: Start QIX Engine
-        command: ACCEPT_EULA=yes docker-compose -f test/docker-compose.yml up -d
-      - run:
-        name: Check that QIX Engine is up and running
-        command: |
-            set +e
-            # Check that Engine is running
-            ENGINE_ID=$(docker ps -aqf "name=engine")
-            echo "Engine container id is $ENGINE_ID"
-            RETRIES=0
-            while [[ "$ENGINE_STATUS" != "running" && $RETRIES -le 30 ]]; do
-              ENGINE_STATUS=$(docker inspect -f '{{.State.Status}}' "$ENGINE_ID")
-              echo "Engine status is $ENGINE_STATUS"
-              sleep 2
-              RETRIES=$[$RETRIES+1]
-            done
-            if [[ "$ENGINE_STATUS" != "running"  ]]; then
-              echo "QIX Engine did not start up properly"
-              exit 1
-            fi
-      - run:
-        name: Integration Test
-        command: ./test/test.sh
+      # - run:
+      #   name: Login to Docker
+      #   command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
+      # - run:
+      #   name: Start QIX Engine
+      #   command: ACCEPT_EULA=yes docker-compose -f test/docker-compose.yml up -d
+      # - run:
+      #   name: Check that QIX Engine is up and running
+      #   command: |
+      #       set +e
+      #       # Check that Engine is running
+      #       ENGINE_ID=$(docker ps -aqf "name=engine")
+      #       echo "Engine container id is $ENGINE_ID"
+      #       RETRIES=0
+      #       while [[ "$ENGINE_STATUS" != "running" && $RETRIES -le 30 ]]; do
+      #         ENGINE_STATUS=$(docker inspect -f '{{.State.Status}}' "$ENGINE_ID")
+      #         echo "Engine status is $ENGINE_STATUS"
+      #         sleep 2
+      #         RETRIES=$[$RETRIES+1]
+      #       done
+      #       if [[ "$ENGINE_STATUS" != "running"  ]]; then
+      #         echo "QIX Engine did not start up properly"
+      #         exit 1
+      #       fi
+      # - run:
+      #   name: Integration Test
+      #   command: ./test/test.sh
