Trying another approach

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,41 +28,59 @@ jobs:
           command: go test -v -race ./...
       - setup_remote_docker
       - run:
-          name: Login to Docker
-          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
-      - run:
-          name: Start QIX Engine
-          command: ACCEPT_EULA=yes docker-compose -f test/docker-compose.yml up -d
-      - run:
-          name: Check that QIX Engine is up and running
+          name: Run Integration Test
           command: |
-              set +e
-              # Check that Engine is running
-              ENGINE_ID=$(docker ps -aqf "name=engine")
-              echo "Engine container id is $ENGINE_ID"
-              RETRIES=0
-              while [[ "$ENGINE_STATUS" != "running" && $RETRIES -le 30 ]]; do
-                ENGINE_STATUS=$(docker inspect -f '{{.State.Status}}' "$ENGINE_ID")
-                echo "Engine status is $ENGINE_STATUS"
-                sleep 2
-                RETRIES=$[$RETRIES+1]
-              done
-              if [[ "$ENGINE_STATUS" != "running"  ]]; then
-                echo "QIX Engine did not start up properly"
-                exit 1
-              fi
-      - run:
-          name: Integration Test
-          working_directory: /go
-          command: |
-              set +e
-              ENGINE_CONTAINER_ID=$(docker ps -aqf "name=engine")
-              TEST_CONTAINER_ID=$(docker run -d golang:1.9-alpine tail -f /dev/null)
-              ENGINE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $ENGINE_CONTAINER_ID)
-              docker cp /go/src/github.com/qlik-oss/core-cli/test/apps/ $ENGINE_CONTAINER_ID:/apps
-              docker cp /go/src/github.com/qlik-oss/core-cli/test/data/ $ENGINE_CONTAINER_ID:/data
-              echo "Engine Container IP is $ENGINE_IP"
-              docker cp . $TEST_CONTAINER_ID:/go
-              docker exec $TEST_CONTAINER_ID /bin/sh -c 'apk update && apk add --no-cache socat bash make'
-              docker exec -d $TEST_CONTAINER_ID /bin/bash -c "socat TCP-LISTEN:9076,fork TCP:$ENGINE_IP:9076"
-              docker exec $TEST_CONTAINER_ID /bin/bash -c "go test /go/src/github.com/qlik-oss/core-cli/test/cli_integration_test.go --engineIP $ENGINE_IP:9076"
+            # Spin up environment
+            ACCEPT_EULA=yes docker-compose -f test/docker-compose.yml up -d
+            CONTAINER_ID=$(docker ps -aqf "name=engine")
+            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$CONTAINER_ID")
+            # Start a container for test execution
+            TEST_CONTAINER=$(docker run -e TEST_HOST=$TEST_HOST -d golang:1.9-alpine tail -f /dev/null)
+            # Install packages
+            docker exec $TEST_CONTAINER sh -c 'apk update && apk add --no-cache make'
+            # Copy code into container
+            docker cp /go/src/github.com/qlik-oss/core-cli/ $TEST_CONTAINER:/go/src/qlik-oss/core-cli/
+            # Execute tests
+            docker exec $TEST_CONTAINER sh -c 'go test -timeout 30s /go/src/qlik-oss/core-cli/test/cli_integration_test.go --engineIP $TEST_HOST:9076"'
+            # Bring down the docker-compose and test container
+            docker-compose -f test/docker-compose.yml down
+            docker kill $TEST_CONTAINER
+      # - run:
+      #     name: Login to Docker
+      #     command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
+      # - run:
+      #     name: Start QIX Engine
+      #     command: ACCEPT_EULA=yes docker-compose -f test/docker-compose.yml up -d
+      # - run:
+      #     name: Check that QIX Engine is up and running
+      #     command: |
+      #         set +e
+      #         # Check that Engine is running
+      #         ENGINE_ID=$(docker ps -aqf "name=engine")
+      #         echo "Engine container id is $ENGINE_ID"
+      #         RETRIES=0
+      #         while [[ "$ENGINE_STATUS" != "running" && $RETRIES -le 30 ]]; do
+      #           ENGINE_STATUS=$(docker inspect -f '{{.State.Status}}' "$ENGINE_ID")
+      #           echo "Engine status is $ENGINE_STATUS"
+      #           sleep 2
+      #           RETRIES=$[$RETRIES+1]
+      #         done
+      #         if [[ "$ENGINE_STATUS" != "running"  ]]; then
+      #           echo "QIX Engine did not start up properly"
+      #           exit 1
+      #         fi
+      # - run:
+      #     name: Integration Test
+      #     working_directory: /go
+      #     command: |
+      #         set +e
+      #         ENGINE_CONTAINER_ID=$(docker ps -aqf "name=engine")
+      #         TEST_CONTAINER_ID=$(docker run -d golang:1.9-alpine tail -f /dev/null)
+      #         ENGINE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $ENGINE_CONTAINER_ID)
+      #         docker cp /go/src/github.com/qlik-oss/core-cli/test/apps/ $ENGINE_CONTAINER_ID:/apps
+      #         docker cp /go/src/github.com/qlik-oss/core-cli/test/data/ $ENGINE_CONTAINER_ID:/data
+      #         echo "Engine Container IP is $ENGINE_IP"
+      #         docker cp . $TEST_CONTAINER_ID:/go
+      #         docker exec $TEST_CONTAINER_ID /bin/sh -c 'apk update && apk add --no-cache socat bash make'
+      #         docker exec -d $TEST_CONTAINER_ID /bin/bash -c "socat TCP-LISTEN:9076,fork TCP:$ENGINE_IP:9076"
+      #         docker exec $TEST_CONTAINER_ID /bin/bash -c "go test /go/src/github.com/qlik-oss/core-cli/test/cli_integration_test.go --engineIP $ENGINE_IP:9076"
